language: android
jdk:
  - oraclejdk8
sudo: required

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

env:
  global:
    - ADB_INSTALL_TIMEOUT=20

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - android-21
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

  licenses:
     - 'android-sdk-license-.+'

before_install:
  - chmod +x gradlew
  - android list targets
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

before_script:
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
- ./gradlew build
